version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  db:
    build:
      context: .
    expose:
      - "5432"
    image: postgres:10-alpine
    container_name: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTFRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - djangonetwork

networks:
    djangonetwork:
      driver: bridge